# Generated by Django 3.1.7 on 2021-05-23 14:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fallower',
            name='fallowing',
            field=models.ManyToManyField(related_name='fallowing_list', to=settings.AUTH_USER_MODEL),
        ),
    ]
