# Generated by Django 3.1.7 on 2021-07-04 17:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0005_auto_20210703_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='passangers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ride',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='ride',
            name='seats',
            field=models.IntegerField(default=5),
        ),
    ]
