# Generated by Django 3.1.7 on 2021-07-14 12:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0007_ride_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField(blank=True, max_length=255)),
                ('rate', models.PositiveSmallIntegerField(choices=[(1, 'Very bad'), (2, 'Bad'), (3, 'Good'), (4, 'Very nice'), (5, 'Excellent')])),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ride', to='carpool.ride')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
