# Generated by Django 3.1.7 on 2021-07-14 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0011_auto_20210714_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='text',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
