# Generated by Django 3.1.7 on 2021-08-16 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0013_auto_20210815_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driven_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
