# Generated by Django 3.1.7 on 2021-09-15 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0014_rating_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='phoneNumber',
            field=models.CharField(default='+371 26179999', max_length=15),
        ),
    ]
